# change the followings to match your Github username and repo name
baseurl: "/johndoe" # the name of your github repo
url: "https://harrywang.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "John Doe's Website"
description: John's personal website

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: John Doe
author-bio: Designer and Woodworker  # change to false to hide
author-image: johndoe.jpeg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Skills
  permalink: skills
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/
facebook: https://facebook.com/
instagram: false
github: https://github.com/
linkedin: false
medium: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
